language: R
cache:
  packages: true
  directories:
  - _bookdown_files

pandoc_version: 2.1.1

r_github_packages:
- hadley/r4ds
- cienciadedatos/datos

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

