language: R
sudo: required
cache:
  directories:
  - _book
  - $HOME/.npm

r:
  - release

repos:
  CRAN: https://cloud.r-project.org

addons:
  apt:
    packages:
      - libxml2-dev

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
