rmd_files: [
  "index.Rmd",
  "intro.Rmd",
  "visualize.Rmd",
  "transform.Rmd",
  "tidy.Rmd",
  "model.Rmd",
  "import.Rmd",
  "eda.Rmd",
  "rmarkdown.Rmd",
  "shiny.Rmd",
  "data-structures.Rmd",
  "functions.Rmd",
  "strings.Rmd",
  "datetimes.Rmd",
  "lists.Rmd",
  "model-vis.Rmd",
  "model-assess.Rmd",
]

